<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:xiid="http://www.osci.de/xinneres/idnr/2"
           xmlns:din91379="urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08"
           xmlns:xida="http://www.osci.de/xinneres/datum/2"
           targetNamespace="http://www.osci.de/xinneres/idnr/2"
           version="2"
           elementFormDefault="unqualified"
           attributeFormDefault="unqualified">
   <xs:annotation>
      <xs:appinfo>
         <standard>
            <nameLang>XInneres-Basismodul</nameLang>
            <nameKurz>XInneres-Basismodul</nameKurz>
            <nameTechnisch>xinneres.basismodul</nameTechnisch>
            <kennung>urn:xoev-de:kosit:standard:xinneres.basismodul</kennung>
            <beschreibung>Im Auftrag des AK I hat die PG Standard bisher unter anderem die fachlichen Vorgaben und die Struktur der Meldeanschrift für die Bereiche Ausländer-, Melde- und Personenstandswesen harmonisiert. Der vorliegende Standard XInneres bildet auf technischer Ebene eine Klammer vor den Standards der Innenverwaltung. An dieser Stelle können gemeinsam genutzte Komponenten definiert werden. In der ersten Version von XInneres definiert der Standard die Datentypen für die Darstellung der Meldeanschrift.</beschreibung>
         </standard>
         <versionStandard>
            <version>26.11</version>
            <versionXOEVProfil>3.0.3</versionXOEVProfil>
            <versionXOEVHandbuch>3.0.2</versionXOEVHandbuch>
            <versionXGenerator>3.2.4</versionXGenerator>
            <versionModellierungswerkzeug>19.0 SP4</versionModellierungswerkzeug>
            <nameModellierungswerkzeug>MagicDraw</nameModellierungswerkzeug>
         </versionStandard>
         <title>Identifikationsnummer</title>
      </xs:appinfo>
   </xs:annotation>
   <xs:import schemaLocation="http://www.osci.de/xinneres/datum/2/xinneres-datum.xsd"
              namespace="http://www.osci.de/xinneres/datum/2"/>
   <xs:import schemaLocation="https://xoev.de/schemata/din/91379/2022-08/din-norm-91379-datatypes.xsd"
              namespace="urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08"/>
   <xs:simpleType name="Identifikationsnummer">
      <xs:annotation>
         <xs:appinfo>
            <title>Identifikationsnummer</title>
         </xs:appinfo>
         <xs:documentation>Mit diesem Datentyp wird die Identifikationsnummer nach § 139b AO oder in Verbindung mit §§ 1, 2 und 5 IDNrG abgebildet. Sie besteht aus einer elfstelligen Ziffernfolge. Die elfte Stelle ist eine Prüfziffer. Die erste Stelle der idnr wird nie mit der Ziffer 0 belegt. Ausnahme: Für Testzwecke ist vom BZSt ein eigener Nummernkreis von Identifikationsnummern vorgesehen. Identifikationsnummern zu Testzwecken beginnen zur Unterscheidung von produktiven Identifikationsnummern immer mit einer Null (0). Die Prüfziffer berechnet sich wie folgt (Algorithmus in Pseudo-Code): cpos steht für eine der Ziffern an den Positionen 1 (c1) bis 10 (c10). pz ist die Prüfziffer. pos, m11, m10 sind Hilfsvariablen. begin m11 := 10 m10 := 0 for pos = 1 to 10 step 1 m10 := (cpos + m11) mod 10 if m10 = 0 then m10 := 10 end-if m11 := (2 * m10) mod 11 end-for pz := 11 - m11 if pz = 10 then pz := 0 end-if end.</xs:documentation>
      </xs:annotation>
      <xs:restriction base="din91379:datatypeC">
         <xs:pattern value="\d{11}"/>
      </xs:restriction>
   </xs:simpleType>
   <xs:complexType name="PlausibilisierteIdentifikationsnummer">
      <xs:annotation>
         <xs:appinfo>
            <title>Plausibilisierte Identifikationsnummer</title>
         </xs:appinfo>
         <xs:documentation>Mit diesem Datentyp werden die Identifikationsdaten einer Person auf der Basis einer Identifikationsnummer nach § 139b AO oder in Verbindung mit §§ 1, 2 und 5 IDNrG und eines plausibilisierenden Geburtsdatums abgebildet.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="idNr" type="xiid:Identifikationsnummer">
            <xs:annotation>
               <xs:documentation>Mit diesem Element wird die Identifikationsnummer nach § 139b AO oder in Verbindung mit §§ 1, 2 und 5 IDNrG der Person übermittelt.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="geburtsdatum" type="xida:TeilbekanntesDatumMitUnbekannt">
            <xs:annotation>
               <xs:documentation>Mit diesem Element wird das Geburtsdatum der Person übermittelt.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
</xs:schema>
