<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:xauslaender="http://www.osci.de/xauslaender2611"
           xmlns:din91379="urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08"
           xmlns:xian="http://www.osci.de/xinneres/allgemeinername/4"
           xmlns:xida="http://www.osci.de/xinneres/datum/2"
           targetNamespace="http://www.osci.de/xauslaender2611"
           version="26.11"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">
   <xs:annotation>
      <xs:appinfo>
         <standard>
            <nameLang>XAusländer</nameLang>
            <nameKurz>XAusländer</nameKurz>
            <nameTechnisch>xinneres.xauslaender</nameTechnisch>
            <kennung>urn:xoev-de:kosit:standard:xinneres.xauslaender</kennung>
            <beschreibung>Das Fachmodul XAusländer des Standards XInneres beschreibt die Datenübermittlung im Ausländerwesen.</beschreibung>
         </standard>
         <versionStandard>
            <version>26.11</version>
            <versionXOEVProfil>3.0.3</versionXOEVProfil>
            <versionXOEVHandbuch>2.4</versionXOEVHandbuch>
            <versionXGenerator>3.0.1</versionXGenerator>
            <versionModellierungswerkzeug>19.0 SP4</versionModellierungswerkzeug>
            <nameModellierungswerkzeug>MagicDraw</nameModellierungswerkzeug>
         </versionStandard>
      </xs:appinfo>
   </xs:annotation>
   <xs:include schemaLocation="xauslaender-nachrichten-bamf-abh.xsd"/>
   <xs:import schemaLocation="http://www.osci.de/xinneres/allgemeinername/4/xinneres-name.xsd"
              namespace="http://www.osci.de/xinneres/allgemeinername/4"/>
   <xs:import schemaLocation="http://www.osci.de/xinneres/datum/2/xinneres-datum.xsd"
              namespace="http://www.osci.de/xinneres/datum/2"/>
   <xs:import schemaLocation="https://xoev.de/schemata/din/91379/2022-08/din-norm-91379-datatypes.xsd"
              namespace="urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08"/>
   <xs:complexType name="AbschlusstestdatenSprache">
      <xs:annotation>
         <xs:documentation>Dieses Element enthält die Daten zu einem Abschlusstest des Integrationskurses.</xs:documentation>
      </xs:annotation>
      <xs:complexContent>
         <xs:extension base="xauslaender:Abschlusstestdaten">
            <xs:sequence>
               <xs:element name="abschlusstestart"
                           type="xauslaender:Code.Int.Abschlusstestartsprache">
                  <xs:annotation>
                     <xs:documentation>Es wird die Art des Abschlusstests übermittelt.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="gesamtergebnis"
                           minOccurs="0"
                           type="xauslaender:Code.Int.Abschlusstestdatensprache">
                  <xs:annotation>
                     <xs:documentation>Es wird das erreichte Sprachniveau übermittelt (unter A2, A2, B1).</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="ergebnisHoeren"
                           minOccurs="0"
                           type="xauslaender:Code.Int.Abschlusstestergebnisinterpretation">
                  <xs:annotation>
                     <xs:documentation>Es wird das erreichte Teilergebnis mit einer Interpretationshilfe (z.B. "A2 sehr gut erfüllt", "B1 erfüllt", etc.) übermittelt.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="fertigkeitHoeren" minOccurs="0" type="din91379:datatypeC">
                  <xs:annotation>
                     <xs:documentation>Es werden die erreichten Punktzahlen (z.B. "10 von 25") übermittelt.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="ergebnisSchreiben"
                           minOccurs="0"
                           type="xauslaender:Code.Int.Abschlusstestergebnisinterpretation">
                  <xs:annotation>
                     <xs:documentation>Es wird das erreichte Teilergebnis mit einer Interpretationshilfe (z.B. "A2 sehr gut erfüllt", "B1 erfüllt", etc.) übermittelt.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="fertigkeitSchreiben" minOccurs="0" type="din91379:datatypeC">
                  <xs:annotation>
                     <xs:documentation>Es werden die erreichten Punktzahlen (z.B. "10 von 25") übermittelt.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="ergebnisSprechen"
                           minOccurs="0"
                           type="xauslaender:Code.Int.Abschlusstestergebnisinterpretation">
                  <xs:annotation>
                     <xs:documentation>Es wird das erreichte Teilergebnis mit einer Interpretationshilfe (z.B. "A2 sehr gut erfüllt", "B1 erfüllt", etc.) übermittelt.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="fertigkeitSprechen" minOccurs="0" type="din91379:datatypeC">
                  <xs:annotation>
                     <xs:documentation>Es werden die erreichten Punktzahlen (z.B. "10 von 25") übermittelt.</xs:documentation>
                  </xs:annotation>
               </xs:element>
            </xs:sequence>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>
   <xs:complexType name="Int.Ansprechpartner">
      <xs:annotation>
         <xs:appinfo>
            <title>Der Ansprechpartner in der Kommunikation mit den TGS</title>
         </xs:appinfo>
         <xs:documentation>Mit diesem Element werden Kontaktdaten für einen Ansprechpartner beschrieben, welcher bezogen auf den Sachverhalt einer Nachricht Auskunft geben kann. In der Regel dürfte dies die Person sein, die die Nachricht ausgelöst hat. Sofern ein Ansprechpartner vorhanden ist, sind dessen Kontaktdaten anzugeben. Dies gilt insbesondere bei Nachrichten, die voraussichtlich zu Rückfragen führen. Im Fall einer funktionsbezogenen Kontaktstelle ist auf jeden Fall das Organisationszeichen zu befüllen, Vorname und Nachname entfallen dann.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="organisationszeichen" minOccurs="0" type="din91379:datatypeC">
            <xs:annotation>
               <xs:documentation>Dieses Element bezeichnet das Merkmal, das den Ansprechpartner für den jeweiligen Sachverhalt identifiziert.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="familienname" minOccurs="0" type="xian:AllgemeinerName"/>
         <xs:element name="vorname" minOccurs="0" type="xian:AllgemeinerName"/>
         <xs:element name="kontaktdaten"
                     maxOccurs="unbounded"
                     type="xauslaender:Kommunikation"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="Int.Dienststelle">
      <xs:annotation>
         <xs:appinfo>
            <title>Die Dienststelle in der Kommunikation mit den Trägern der Grundsicherung</title>
         </xs:appinfo>
         <xs:documentation>Eine Dienststelle in der Kommunikation mit den Trägern der Grundsicherung ist eine Verwaltungseinheit mit organisatorischer und sachlicher Selbstständigkeit. Sie nimmt einen eigenen Aufgabenbereich wahr.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="dstNummer" type="xauslaender:Code.Int.Dienststelle">
            <xs:annotation>
               <xs:documentation>Die Dienststellennummer ist eine eindeutige Kennung zur Identifizierung einer Dienststelle.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="dstBezeichnung" minOccurs="0" type="din91379:datatypeC">
            <xs:annotation>
               <xs:documentation>Mit diesem Element kann eine Kurzbezeichnung der Dienststelle angegeben werden.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="kontaktdaten"
                     maxOccurs="unbounded"
                     type="xauslaender:Kommunikation"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="Int.WeitereAngabenBAMFTGS">
      <xs:annotation>
         <xs:documentation>Mit diesem Datentyp werden weitere Angaben zur betroffenen Person übermittelt. Implementierungshinweis: Diese Angaben dürfen nicht auf dem Zulassungs-/Verpflichtungsschein angegeben werden.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="staatsangehoerigkeit"
                     maxOccurs="4"
                     type="xauslaender:AngabenZumStaat"/>
         <xs:element name="aufenthaltstitel" type="xauslaender:Code.Int.Aufenthaltstitel"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="Nachricht.G2G.XA.Int.BAMFTGS">
      <xs:annotation>
         <xs:documentation>Dieses Element wird bei jeder Nachricht zwischen dem BAMF und dem TGS im Themenkreis Integration verwendet.</xs:documentation>
      </xs:annotation>
      <xs:complexContent>
         <xs:extension base="xauslaender:Nachricht.G2G.XA.erweitert">
            <xs:sequence>
               <xs:element name="geschaeftszeichen" minOccurs="0" type="din91379:datatypeC">
                  <xs:annotation>
                     <xs:documentation>Das Geschäftszeichen erlaubt dem Autor der Nachricht den auslösenden Vorgang bei Rückfragen schnell (im Vergleich zur Suche mit Personendaten) zu identifizieren.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="ansprechpartner"
                           minOccurs="0"
                           type="xauslaender:Int.Ansprechpartner"/>
               <xs:element name="dienststelleBA"
                           minOccurs="0"
                           type="xauslaender:Int.Dienststelle">
                  <xs:annotation>
                     <xs:documentation>Mit diesem Element werden Angaben zu einer Dienststelle im Verantwortungsbereich der Bundesagentur für Arbeit übermittelt.</xs:documentation>
                  </xs:annotation>
               </xs:element>
            </xs:sequence>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>
   <xs:complexType name="ZulassungVerpflichtung.BAMFTGS">
      <xs:annotation>
         <xs:documentation>Hiermit werden die Daten der akzeptierten Zulassung/Verpflichtung, so wie sie in InGe abgelegt sind, übermittelt.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="art" type="xauslaender:Code.BAMFABH.ArtDerBerechtigung">
            <xs:annotation>
               <xs:documentation>Mit diesem Element wird die Art der Zulassung/Verpflichtung übermittelt.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="bamfkennziffer" type="din91379:datatypeC">
            <xs:annotation>
               <xs:documentation>Mit diesem Element wird die BAMF-Kennziffer der akzeptierten bestehenden Zulassung/Verpflichtung übermittelt.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="gueltigVon" type="xida:Tagesdatum">
            <xs:annotation>
               <xs:documentation>Mit diesem Element wird der Beginn der Zulassung/Verpflichtung mitgeteilt.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="gueltigBis" type="xida:Tagesdatum">
            <xs:annotation>
               <xs:documentation>Mit diesem Element wird das in der Zulassung/Verpflichtung festgelegte Gültigkeitsende mitgeteilt.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="teilnahmeUnbefristet" type="xs:boolean">
            <xs:annotation>
               <xs:documentation>Wenn die Angaben in InGe besagen, dass die Teilnahme unbefristet möglich ist, wird dies mit diesem Element übermittelt.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="austellendeBehoerde" type="xauslaender:Behoerde">
            <xs:annotation>
               <xs:documentation>Mit diesem Element wird übermittelt, wer die Zulassung/Verpflichtung ausgestellt hat.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:element name="TGSBAMF.Teilnahmezulassung.080001">
      <xs:annotation>
         <xs:appinfo>
            <autor>Träger der Grundsicherung (dbs)</autor>
            <leser>Bundesamt für Migration und Flüchtlinge (dbs)</leser>
            <rechtsgrundlage>§ 88a AufenthG, § 8 IntV</rechtsgrundlage>
         </xs:appinfo>
         <xs:documentation>Mit dieser Nachricht werden die Daten zu einer Zulassung gem. § 5a Abs. 1 IntV übermittelt. Diese Nachricht beinhaltet gleichzeitig das Auskunftsersuchen gemäß § 8 Abs. 1 Satz 2 IntV.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xauslaender:Nachricht.G2G.XA.Int.BAMFTGS">
               <xs:sequence>
                  <xs:element name="personalien" type="xauslaender:Personalien.Int.ABHBAMF"/>
                  <xs:element name="bamfkennziffer" minOccurs="0" type="din91379:datatypeC">
                     <xs:annotation>
                        <xs:documentation>Sofern der Behörde eine bestehende BAMF-Kennziffer zu der Person bekannt ist, ist diese zu Identifizierungszwecken zu übermitteln.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="gueltigBis" type="xida:Tagesdatum">
                     <xs:annotation>
                        <xs:documentation>Mit diesem Datum wird das Ende der Zulassung übermittelt.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="weitereAngaben" type="xauslaender:Int.WeitereAngabenBAMFTGS"/>
               </xs:sequence>
            </xs:extension>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="BAMFTGS.ZulassungVerpflichtung.Akzeptanz.080003">
      <xs:annotation>
         <xs:appinfo>
            <autor>Träger der Grundsicherung (dbs)</autor>
            <leser>Bundesamt für Migration und Flüchtlinge (dbs)</leser>
            <rechtsgrundlage>§ 88a AufenthG, § 8 IntV</rechtsgrundlage>
            <title>Akzeptanz einer Zulassung/Verpflichtung</title>
         </xs:appinfo>
         <xs:documentation>Mit dieser Nachricht teilt das BAMF dem TGS mit, dass die übermittelten Daten zur Zulassung/Verpflichtung akzeptiert und gespeichert wurden.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xauslaender:Nachricht.G2G.XA.Int.BAMFTGS">
               <xs:sequence>
                  <xs:element name="zulassungVerpflichtung"
                              type="xauslaender:ZulassungVerpflichtung.BAMFTGS">
                     <xs:annotation>
                        <xs:documentation>Übermittelt werden die Daten der akzeptierten Berechtigung oder Verpflichtung, so wie sie in InGe abgelegt sind.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="abgeloesteBerechtigung"
                              minOccurs="0"
                              type="xauslaender:BerechtigungVerpflichtung">
                     <xs:annotation>
                        <xs:documentation>Die übermittelte Zulassung/Verpflichtung hat eine bereits bestehende Berechtigung mit den in diesem Element enthaltenen Daten abgelöst.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="informationSachbearbeitung"
                              minOccurs="0"
                              maxOccurs="unbounded"
                              type="xauslaender:Code.Int.InformationBerechtigungVerpflichtung">
                     <xs:annotation>
                        <xs:documentation>Mit diesem Element werden Hinweise für die Sachbearbeitung übermittelt.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
               </xs:sequence>
            </xs:extension>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="BAMFTGS.Dublette.080004">
      <xs:annotation>
         <xs:appinfo>
            <autor>Bundesamt für Migration und Flüchtlinge (dbs)</autor>
            <leser>Träger der Grundsicherung (dbs)</leser>
            <rechtsgrundlage>§ 88a AufenthG, § 8 IntV</rechtsgrundlage>
         </xs:appinfo>
         <xs:documentation>Mit dieser Nachricht teilt das BAMF mit, dass eine Person mit den Identifikationsmerkmalen Nachname, Geburtsdatum, Geschlecht, aus der soeben übermittelten Zulassung/Verpflichtung bereits im Datenbestand von InGe vorhanden ist.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xauslaender:Nachricht.G2G.XA.Int.BAMFTGS">
               <xs:sequence>
                  <xs:element name="informationSachbearbeitung"
                              type="xauslaender:Code.BAMFABH.Dublettenmeldung">
                     <xs:annotation>
                        <xs:documentation>Mit diesem Element wird der Grund für die Dublettenmeldung übermittelt.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
               </xs:sequence>
            </xs:extension>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="BAMFTGS.ZulassungVerpflichtungNichtMoeglich.080005">
      <xs:annotation>
         <xs:appinfo>
            <autor>Bundesamt für Migration und Flüchtlinge (dbs)</autor>
            <leser>Träger der Grundsicherung (dbs)</leser>
            <rechtsgrundlage>§ 88a AufenthG, § 8 IntV</rechtsgrundlage>
         </xs:appinfo>
         <xs:documentation>Mit dieser Nachricht teilt das BAMF mit, dass und aus welchem Grund keine neue Zulassung/Verpflichtung möglich ist.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xauslaender:Nachricht.G2G.XA.Int.BAMFTGS">
               <xs:sequence>
                  <xs:element name="ablehnungsgrund" type="xauslaender:Code.BAMFABH.Ablehnungsgrund">
                     <xs:annotation>
                        <xs:documentation>Mit diesem Element wird der Grund für die Ablehnung mitgeteilt.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="beschreibung" type="din91379:datatypeC">
                     <xs:annotation>
                        <xs:documentation>Mit diesem Element wird der Grund für die Ablehnung beschrieben.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="aktuelleBerechtigungVerpflichtung"
                              minOccurs="0"
                              type="xauslaender:BerechtigungVerpflichtung">
                     <xs:annotation>
                        <xs:documentation>Mit diesem Element werden Informationen zu der Berechtigung oder Verpflichtung übermittelt, die zum Zeitpunkt der Erzeugung dieser Nachricht gültig ist und die Ablehnung begründet.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="kannUebernommenWerden" type="xs:boolean">
                     <xs:annotation>
                        <xs:documentation>Wird mit diesem Element der Wert true übermittelt, ist der Sachbearbeitung kenntlich zu machen, dass die Verpflichtung unter Nutzung der entsprechenden Nachricht übernommen werden kann.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="informationSachbearbeitung"
                              minOccurs="0"
                              maxOccurs="unbounded"
                              type="xauslaender:Code.Int.InformationBerechtigungVerpflichtung">
                     <xs:annotation>
                        <xs:documentation>Mit diesem Element werden Informationen über die Möglichkeit der Übernahme einer bestehenden Verpflichtung, einschließlich der damit verbundenen Vorteile für die übernehmende Stelle übermittelt (z. B. Erhalt von Informationen aus Nachricht 080015).</xs:documentation>
                     </xs:annotation>
                  </xs:element>
               </xs:sequence>
            </xs:extension>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="TGSBAMF.Teilnahmeverpflichtung.080010">
      <xs:annotation>
         <xs:appinfo>
            <autor>Träger der Grundsicherung (dbs)</autor>
            <leser>Bundesamt für Migration und Flüchtlinge (dbs)</leser>
            <rechtsgrundlage>§ 88a AufenthG, § 8 IntV</rechtsgrundlage>
         </xs:appinfo>
         <xs:documentation>Mit dieser Nachricht werden die Daten zu einer Verpflichtung gemäß § 44a Abs. 1 Satz 1 Nr. 2 oder Abs. 1 Satz 3 aufenthg_s übermittelt. Diese Nachricht beinhaltet gleichzeitig das Auskunftsersuchen gemäß § 8 Abs. 1 Satz 2 intv_s.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xauslaender:Nachricht.G2G.XA.Int.BAMFTGS">
               <xs:sequence>
                  <xs:element name="personalien" type="xauslaender:Personalien.Int.ABHBAMF"/>
                  <xs:element name="bamfkennziffer" minOccurs="0" type="din91379:datatypeC">
                     <xs:annotation>
                        <xs:documentation>Sofern der Behörde eine bestehende BAMF-Kennziffer zu der Person bekannt ist, ist diese zu Identifizierungszwecken zu übermitteln.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="gueltigBis" type="xida:Tagesdatum">
                     <xs:annotation>
                        <xs:documentation>Mit diesem Datum wird das Ende der Teilnahmeverpflichtung übermittelt.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="weitereAngaben" type="xauslaender:Int.WeitereAngabenBAMFTGS"/>
               </xs:sequence>
            </xs:extension>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="TGSBAMF.BerechtigungVerpflichtungAuskunftsersuchen.080011">
      <xs:annotation>
         <xs:appinfo>
            <autor>Träger der Grundsicherung (dbs)</autor>
            <leser>Bundesamt für Migration und Flüchtlinge (dbs)</leser>
            <rechtsgrundlage>§ 88a AufenthG, § 8 IntV</rechtsgrundlage>
         </xs:appinfo>
         <xs:documentation>Mit dieser Nachricht bittet der TGS das BAMF um Auskunft über das Bestehen einer Berechtigung oder Verpflichtung für die genannte Person.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xauslaender:Nachricht.G2G.XA.Int.BAMFTGS">
               <xs:sequence>
                  <xs:element name="personalien" type="xauslaender:Personalien.Int.ABHBAMF"/>
                  <xs:element name="bamfkennziffer" minOccurs="0" type="din91379:datatypeC">
                     <xs:annotation>
                        <xs:documentation>Sofern der Behörde eine bestehende BAMF-Kennziffer zu der Person bekannt ist, ist diese zu Identifizierungszwecken zu übermitteln.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
               </xs:sequence>
            </xs:extension>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="BAMFTGS.Berechtigungsscheininhalt.080012">
      <xs:annotation>
         <xs:appinfo>
            <autor>Bundesamt für Migration und Flüchtlinge (dbs)</autor>
            <leser>Träger der Grundsicherung (dbs)</leser>
            <rechtsgrundlage>§ 88a AufenthG, § 8 IntV</rechtsgrundlage>
         </xs:appinfo>
         <xs:documentation>Mit dieser Nachricht übermittelt das BAMF entweder die Daten aus dem Berechtigungsschein oder die Information, dass der Integrationskurs bereits vollständig absolviert wurde oder die Information, dass keine Berechtigung oder Verpflichtung vorliegt.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xauslaender:Nachricht.G2G.XA.Int.BAMFTGS">
               <xs:sequence>
                  <xs:element name="informationBerechtigungsschein"
                              type="xauslaender:InformationBerechtigungsschein"/>
                  <xs:element name="informationSachbearbeiter"
                              type="xauslaender:Code.BAMFABH.InformationBerechtigungsschein">
                     <xs:annotation>
                        <xs:documentation>Dieses Element enthält klarstellende Informationen für die Sachbearbeitung bei Übermittlung des Berechtigungsscheins.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="kannUebernommenWerden" type="xs:boolean">
                     <xs:annotation>
                        <xs:documentation>Wird mit diesem Element der Wert true übermittelt, ist der Sachbearbeitung kenntlich zu machen, dass die Verpflichtung unter Nutzung der entsprechenden Nachricht übernommen werden kann.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="informationSachbearbeitung"
                              minOccurs="0"
                              maxOccurs="unbounded"
                              type="xauslaender:Code.Int.InformationBerechtigungVerpflichtung">
                     <xs:annotation>
                        <xs:documentation>Mit diesem Element werden Informationen über die Möglichkeit der Übernahme einer bestehenden Verpflichtung, einschließlich der damit verbundenen Vorteile für die übernehmende Stelle übermittelt (z. B. Erhalt von Informationen aus Nachricht 080015).</xs:documentation>
                     </xs:annotation>
                  </xs:element>
               </xs:sequence>
            </xs:extension>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="TGSBAMF.AuskunftsersuchenKursteilnahmeZugelassenerVerpflichteter.080013">
      <xs:annotation>
         <xs:appinfo>
            <autor>Träger der Grundsicherung (dbs)</autor>
            <leser>Bundesamt für Migration und Flüchtlinge (dbs)</leser>
            <rechtsgrundlage>§ 88a AufenthG, § 8 IntV</rechtsgrundlage>
         </xs:appinfo>
         <xs:documentation>Mit dieser Nachricht kann der TGS das BAMF um Auskunft über die Anmeldung bzw. das Teilnahmeverhalten eines Zugelassenen/Verpflichteten ersuchen.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xauslaender:Nachricht.G2G.XA.Int.BAMFTGS">
               <xs:sequence>
                  <xs:element name="identifikation" type="xauslaender:Identifikation.Int.ABHBAMF"/>
               </xs:sequence>
            </xs:extension>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="BAMFTGS.AuskunftKursteilnahmeNichtMoeglich.080014">
      <xs:annotation>
         <xs:appinfo>
            <autor>Bundesamt für Migration und Flüchtlinge (dbs)</autor>
            <leser>Träger der Grundsicherung (dbs)</leser>
            <rechtsgrundlage>§ 88a AufenthG, § 8 IntV</rechtsgrundlage>
         </xs:appinfo>
         <xs:documentation>Mit dieser Nachricht teilt das BAMF dem anfragenden TGS mit, dass auf der Basis der vorhandenen Daten eine Auskunft nicht möglich ist.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xauslaender:Nachricht.G2G.XA.Int.BAMFTGS">
               <xs:sequence>
                  <xs:element name="grundCode" type="xauslaender:Code.BAMFABH.AuskunftNichtMoeglich">
                     <xs:annotation>
                        <xs:documentation>Mit diesem Element wird der Grund dafür übermittelt, warum eine Auskunft nicht möglich ist.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="grund" minOccurs="0" type="din91379:datatypeC">
                     <xs:annotation>
                        <xs:documentation>Mit diesem Element wird zusätzlich eine Erläuterung oder Ergänzung der Begründung angegeben, warum eine Auskunft nicht erteilt werden kann.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
               </xs:sequence>
            </xs:extension>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="BAMFTGS.AuskunftKursteilnahme.080015">
      <xs:annotation>
         <xs:appinfo>
            <autor>Bundesamt für Migration und Flüchtlinge (dbs)</autor>
            <leser>Träger der Grundsicherung (dbs)</leser>
            <rechtsgrundlage>§ 88a AufenthG, § 8 IntV</rechtsgrundlage>
            <title>Auskunft über alle Daten zur Kursteilnahme</title>
         </xs:appinfo>
         <xs:documentation>Mit dieser Nachricht übermittelt das BAMF dem TGS Informationen zur Anmeldung und Kursteilnahme eines TGS-Zugelassenen/TGS-Verpflichteten.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xauslaender:Nachricht.G2G.XA.Int.BAMFTGS">
               <xs:sequence>
                  <xs:element name="kursabbruch" minOccurs="0" fixed="true" type="xs:boolean">
                     <xs:annotation>
                        <xs:documentation>Sofern der Kursträger nach einer entsprechenden Mitteilung durch den Teilnehmer den Kursabbruch eines TGS-Zugelassenen/TGS-Verpflichteten gemeldet hat, wird diese Information hiermit an den TGS weitergegeben. Dies schließt eine spätere Wiederaufnahme der Teilnahme nicht aus.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="kursanmeldedaten"
                              minOccurs="0"
                              type="xauslaender:Kursanmeldedaten"/>
                  <xs:element name="kursabschnittsdaten"
                              minOccurs="0"
                              maxOccurs="unbounded"
                              type="xauslaender:Kursabschnittsdaten"/>
                  <xs:element name="datenAbschlusstestSprache"
                              minOccurs="0"
                              maxOccurs="unbounded"
                              type="xauslaender:AbschlusstestdatenSprache">
                     <xs:annotation>
                        <xs:documentation>Dieses Element enthält die Daten zu Abschlusstests des Sprachkurses.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="datenAbschlusstestOrientierung"
                              minOccurs="0"
                              maxOccurs="unbounded"
                              type="xauslaender:Abschlusstestdaten">
                     <xs:annotation>
                        <xs:documentation>Dieses Element enthält die Daten zu Abschlusstests des Orientierungskurses.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="abgelaufeneBerechtigungVerpflichtung"
                              minOccurs="0"
                              maxOccurs="unbounded"
                              type="xauslaender:BerechtigungVerpflichtungAbgelaufen"/>
                  <xs:element name="datumFruehereKursanmeldung"
                              minOccurs="0"
                              maxOccurs="unbounded"
                              type="xida:Tagesdatum">
                     <xs:annotation>
                        <xs:documentation>Mit diesem Element wird das frühere Anmeldedatum zu nicht mehr gültigen Berechtigungs- und Verpflichtungsvorgängen übermittelt.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="fruehereKursabschnittsdaten"
                              minOccurs="0"
                              maxOccurs="unbounded"
                              type="xauslaender:FruehereKursabschnittsdaten">
                     <xs:annotation>
                        <xs:documentation>Mit diesem Element werden frühere Kursdaten zu nicht mehr gültigen Berechtigungs- und Verpflichtungsvorgängen übermittelt.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="datumFruehererAbschlusstestSprache"
                              minOccurs="0"
                              maxOccurs="unbounded"
                              type="xida:Tagesdatum">
                     <xs:annotation>
                        <xs:documentation>Dieses Element übermittelt das Datum, an dem der Test im Rahmen von nicht mehr gültigen Berechtigungs- und Verpflichtungsvorgängen stattgefunden hat.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="datumFruehererAbschlusstestOrientierung"
                              minOccurs="0"
                              maxOccurs="unbounded"
                              type="xida:Tagesdatum">
                     <xs:annotation>
                        <xs:documentation>Dieses Element übermittelt das Datum, an dem der Test im Rahmen von nicht mehr gültigen Berechtigungs- und Verpflichtungsvorgängen stattgefunden hat.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="informationBerechtigungVerpflichtung"
                              minOccurs="0"
                              maxOccurs="unbounded"
                              type="xauslaender:InformationBerechtigungVerpflichtung">
                     <xs:annotation>
                        <xs:documentation>Mit diesem Element werden Informationen zur Berechtigung/Verpflichtung übermittelt. Falls mehrere erloschene Vorgänge vorliegen sollen alle übermittelt werden, damit der Leser die Betroffenheit seiner Vorgänge ermitteln kann.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
               </xs:sequence>
            </xs:extension>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="TGSBAMF.VerpflichtungUebernahmeAuskunft.080016">
      <xs:annotation>
         <xs:appinfo>
            <autor>Träger der Grundsicherung (dbs)</autor>
            <leser>Bundesamt für Migration und Flüchtlinge (dbs)</leser>
            <rechtsgrundlage>§ 88a AufenthG, § 8 IntV</rechtsgrundlage>
         </xs:appinfo>
         <xs:documentation>Mit dieser Nachricht teilt der TGS dem BAMF mit, dass er eine bereits bestehende Verpflichtung übernehmen will. Gleichzeitig stellt diese Nachricht ein Auskunftsersuchen hinsichtlich des Teilnahmeverhaltens eines (durch die ABH oder den TGS) Verpflichteten dar.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xauslaender:Nachricht.G2G.XA.Int.BAMFTGS">
               <xs:sequence>
                  <xs:element name="identifikation" type="xauslaender:Identifikation.Int.ABHBAMF"/>
               </xs:sequence>
            </xs:extension>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="BAMFTGS.VerpflichtungUebernahmeNichtMoeglich.080017">
      <xs:annotation>
         <xs:appinfo>
            <autor>Bundesamt für Migration und Flüchtlinge (dbs)</autor>
            <leser>Träger der Grundsicherung (dbs)</leser>
            <rechtsgrundlage>§ 88a AufenthG, § 8 IntV</rechtsgrundlage>
         </xs:appinfo>
         <xs:documentation>Diese Nachricht ist eine Antwort auf die Nachricht zur Übernahme einer Verpflichtung mit gleichzeitigem Auskunftersuchen zur ordnungsgemäßen Kursteilnahme (nachricht.080016). Mit ihr teilt das BAMF im Fehlerfall (z. B. Person unbekannt, keine Verpflichtung) den Grund dafür mit, dass eine Übernahme nicht möglich ist und somit auch keine Auskunft über das Teilnahmeverhalten erteilt werden kann.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xauslaender:Nachricht.G2G.XA.Int.BAMFTGS">
               <xs:sequence>
                  <xs:element name="grundCode"
                              type="xauslaender:Code.BAMFABH.UebernahmeNichtMoeglich">
                     <xs:annotation>
                        <xs:documentation>Mit diesem Element wird der Grund (Code) dafür übermittelt, warum keine Übernahme einer Verpflichtung möglich ist.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="grund" type="din91379:datatypeC">
                     <xs:annotation>
                        <xs:documentation>Mit diesem Element wird (außerhalb der Codeliste) eine Erläuterung oder Ergänzung der Begründung angegeben, warum keine Übernahme einer Verpflichtung möglich ist.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
               </xs:sequence>
            </xs:extension>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
</xs:schema>
