<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:xauslaender="http://www.osci.de/xauslaender2611"
           xmlns:din91379="urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08"
           xmlns:xibehoerde="http://www.osci.de/xinneres/behoerde/7"
           xmlns:xirts="http://www.osci.de/xinneres/rueckweisung/6"
           targetNamespace="http://www.osci.de/xauslaender2611"
           version="26.11"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">
   <xs:annotation>
      <xs:appinfo>
         <standard>
            <nameLang>XAusländer</nameLang>
            <nameKurz>XAusländer</nameKurz>
            <nameTechnisch>xinneres.xauslaender</nameTechnisch>
            <kennung>urn:xoev-de:kosit:standard:xinneres.xauslaender</kennung>
            <beschreibung>Das Fachmodul XAusländer des Standards XInneres beschreibt die Datenübermittlung im Ausländerwesen.</beschreibung>
         </standard>
         <versionStandard>
            <version>26.11</version>
            <versionXOEVProfil>3.0.3</versionXOEVProfil>
            <versionXOEVHandbuch>2.4</versionXOEVHandbuch>
            <versionXGenerator>3.0.1</versionXGenerator>
            <versionModellierungswerkzeug>19.0 SP4</versionModellierungswerkzeug>
            <nameModellierungswerkzeug>MagicDraw</nameModellierungswerkzeug>
         </versionStandard>
      </xs:appinfo>
   </xs:annotation>
   <xs:include schemaLocation="xauslaender-allgemeine-datentypen.xsd"/>
   <xs:import schemaLocation="http://www.osci.de/xinneres/behoerde/7/xinneres-behoerde.xsd"
              namespace="http://www.osci.de/xinneres/behoerde/7"/>
   <xs:import schemaLocation="http://www.osci.de/xinneres/rueckweisung/6/xinneres-rueckweisung.xsd"
              namespace="http://www.osci.de/xinneres/rueckweisung/6"/>
   <xs:import schemaLocation="https://xoev.de/schemata/din/91379/2022-08/din-norm-91379-datatypes.xsd"
              namespace="urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08"/>
   <xs:complexType name="Rueckweisung.Rueckweisungsgrund">
      <xs:annotation>
         <xs:documentation>Mit diesem Element wird ein Grund übermittelt, aus dem die synchrone Nachricht zurückgewiesen wird. Die allgemeinen Rückweisungsgründe können durch kontextspezifische Gründe erläutert werden. Sofern in diesem Element XInneres-Fachmodul-spezifische Rückweisungsgründe übermittelt werden sollen, ist in dem Kindelement grund der Schlüssel S999 und in den Kindelementen grundSpezifisch ein oder mehrere dem XInneres-Fachmodul entstammende Rückweisungsgründe zu übermitteln.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="grund" type="xauslaender:Code.Fehlercode.Sychron">
            <xs:annotation>
               <xs:documentation>Mit diesem Element wird ein Grund übermittelt, aus dem die Nachricht zurückgewiesen wird. Die im Rahmen der hier zu verwendenden Schlüsseltabelle zur Verfügung gestellten Rückweisungsgründe sind kontextunabhängig und finden daher in allen XInneres-Fachmodulen Anwendung. Sofern der Schlüssel S999 verwendet wird, sind ergänzende Angaben in dem Element grundSpezifisch verpflichtend zu übermitteln.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="grundSpezifisch"
                     minOccurs="0"
                     maxOccurs="unbounded"
                     type="xirts:Rueckweisung.GrundSpezifisch">
            <xs:annotation>
               <xs:documentation>In diesem Element können weitere - im Allgemeinen kontextspezifische Angaben - zu dem Grund übermittelt werden, aus dem die Nachricht zurückgewiesen wird.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:element name="Administration.RueckweisungSynchron.000002">
      <xs:annotation>
         <xs:appinfo>
            <title>Return to Sender-Nachricht für synchrone Kommunikation</title>
         </xs:appinfo>
         <xs:documentation>Mit dieser Nachricht wird eine an eine Behörde gerichtete Nachricht als fehlerhaft an die sendende Behörde zurückgewiesen, die erhaltene Nachricht wurde nicht verarbeitet. Diese Nachricht ist für die Verwendung in synchronen Prozessen konzipiert.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xauslaender:Nachricht.G2G.XA">
               <xs:sequence>
                  <xs:element name="rueckweisung">
                     <xs:annotation>
                        <xs:documentation>Dieses Element beinhaltet die Angaben für die synchrone Rückweisung von Nachrichten.</xs:documentation>
                     </xs:annotation>
                     <xs:complexType>
                        <xs:sequence>
                           <xs:element name="rueckweisendeStelle"
                                       minOccurs="0"
                                       type="xirts:Rueckweisung.RueckweisendeStelle">
                              <xs:annotation>
                                 <xs:documentation>Dieses Kindelement ist nur dann zu übermitteln, wenn die Nachricht nicht von dem ursprünglich adressierten Leser zurückgesandt wird, sondern von einer anderen Stelle (zum Beispiel einer Clearingstelle, die im Auftrag der ursprünglich adressierten Behörde eine Prüfung eingehender Nachrichten nach formalen Kriterien durchführt). Wird dieses Element nicht übermittelt, ist die rückweisende Stelle der zurückgewiesenen Nachricht (Kindelement nachricht) zu entnehmen.</xs:documentation>
                              </xs:annotation>
                           </xs:element>
                           <xs:element name="rueckweisungsgrund"
                                       maxOccurs="unbounded"
                                       type="xauslaender:Rueckweisung.Rueckweisungsgrund">
                              <xs:annotation>
                                 <xs:documentation>In diesem Element werden die Gründe mitgeteilt, aufgrund derer die Nachricht zurückgesandt wird. Generell ist so vorzugehen, dass die Gründe für die Rückweisung so präzise und vollständig wie möglich bezeichnet werden, um eine schnelle Klärung des Sachverhalts zu ermöglichen.</xs:documentation>
                              </xs:annotation>
                           </xs:element>
                           <xs:element name="transportinformationen"
                                       minOccurs="0"
                                       type="xirts:Rueckweisung.Transportinformationen">
                              <xs:annotation>
                                 <xs:documentation>In diesem Element sind Informationen zu übermitteln, die bei dem Empfang einer als fehlerhaft betrachteten Nachricht möglicherweise der Transportebene entnommen werden konnten. Diese Angaben können gemacht werden, um dem Leser/Empfänger einer Rücksendenachricht die Identifikation der als fehlerhaft betrachteten und nunmehr zurückgesandten Nachricht zu erleichtern. Alle Kindelemente dieses Elementes sind optional, da keine verbindlichen Anforderungen an das Transportprotokoll gestellt werden können.</xs:documentation>
                              </xs:annotation>
                           </xs:element>
                           <xs:element name="idNachricht"
                                       minOccurs="0"
                                       type="xauslaender:Identifikation.Nachricht">
                              <xs:annotation>
                                 <xs:documentation>In diesem Kindelement wird die die Rückweisung auslösende fachliche Nachricht identifiziert.</xs:documentation>
                              </xs:annotation>
                           </xs:element>
                        </xs:sequence>
                     </xs:complexType>
                  </xs:element>
               </xs:sequence>
            </xs:extension>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="Administration.Sendungswiederholung.000020">
      <xs:annotation>
         <xs:appinfo>
            <title>Wiederholung einer Sendung</title>
         </xs:appinfo>
         <xs:documentation>In allen Fällen in denen ein synchroner Nachrichtenprozess nicht erfolgreich abgeschlossen werden konnte, ist die ursprüngliche fachliche Nachricht mit Hilfe dieser Container-Nachricht erneut zu versenden. Sollte die Versendung der Container-Nachricht scheitern, ist bei einem weiteren Sendeversuch erneut nur die fachliche Nachricht in dem Container zu transportieren (keine Verschachtelung der Container). Die erneute Versendung der ursprünglichen Nachricht in diesem Container erfolgt ausschließlich in der aktuell gültigen Version des XInneres-Fachmoduls. Diese Regelung gilt sowohl für die Sendungswiederholung als auch für die zu verpackende, ursprüngliche Nachricht.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xauslaender:Nachricht.G2G.XA.erweitert">
               <xs:sequence>
                  <xs:element name="nachrichtentyp" type="xauslaender:Code.Nachrichtentyp">
                     <xs:annotation>
                        <xs:documentation>Die eindeutige Identifizierungsnummer für den Nachrichtentyp.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="nachricht" type="xs:base64Binary">
                     <xs:annotation>
                        <xs:documentation>Dieses Element enthält die ursprüngliche Nachricht. Um technische Probleme mit verschachtelten XML-Dokumenten zu vermeiden, ist der zurückgesandte Inhalt immer base64-codiert zurückzusenden.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
               </xs:sequence>
            </xs:extension>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="Administration.Nichtzustaendigserklaerung.000030">
      <xs:annotation>
         <xs:appinfo>
            <title>Nichtzuständigkeitserklärung</title>
         </xs:appinfo>
         <xs:documentation>Mit dieser Nachricht wird die Nichtzuständigkeit zu einer vorher erhaltenen Fachnachricht erklärt. Der Bezug zur Ursprungsnachricht wird mit dem Element ausloeserUUID hergestellt.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xauslaender:Antwortnachricht.G2G.XA">
               <xs:sequence>
                  <xs:element name="zustaendigeBehoerde"
                              minOccurs="0"
                              type="xibehoerde:BehoerdeMitAnschrift"
                              form="unqualified">
                     <xs:annotation>
                        <xs:documentation>Mit diesem Element werden die Angaben der aus Sicht des Lesers der Ursprungsnachricht zuständigen Behörde übermittelt.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="bemerkung" minOccurs="0" type="din91379:datatypeC">
                     <xs:annotation>
                        <xs:documentation>Mit diesem Element werden Bemerkung zur (Nicht-) Zuständigkeit übermittelt.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
               </xs:sequence>
            </xs:extension>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="Administration.Dokumentenlieferung.Paket.000040">
      <xs:annotation>
         <xs:appinfo>
            <autor>Eingabeverfahren</autor>
            <leser>Ausländerbehörde (azr)</leser>
            <title>Paket einer Aktenlieferung</title>
         </xs:appinfo>
         <xs:documentation>Mit dieser Nachricht werden die Dokumente übermittelt. Sollte die Nachricht größer als 50 MB werden, sind die zu übermittelnden Base64 codierten Inhaltsdaten entsprechend der Beschreibung des Elements dokumentcontainer zu paketieren.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xauslaender:Nachricht.G2G.XA.erweitert">
               <xs:sequence>
                  <xs:element name="dokumentcontainer" type="xs:base64Binary">
                     <xs:annotation>
                        <xs:documentation>Mit diesem Element werden die Dokumente im zip-Archiv übermittelt. Für das verpacken des zip-Archivs ist der DEFLATE- oder STORE-Algorithmus anzuwenden. Die Dokumente liegen flach in der Form ltdokumentuuidgt.ltdokumentformatgt im zip-Archiv vor. Die Zuordnung zu den Metadaten des Dokuments wird über das gleichnamige Kindelement dokumentuuid in den jeweiligen Elementen der Fachnachricht hergestellt. Das Aufteilen der Pakete geschieht auf der Zip-Datei. Die Teile der Zip-Datei werden Base64 übertragen.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="identifikationFachnachricht"
                              type="xauslaender:Identifikation.Nachricht">
                     <xs:annotation>
                        <xs:documentation>Mit diesem Element werden Identifikationsdaten der zugehörigen Fachnachricht übermittelt.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="paketnummer" type="xs:integer">
                     <xs:annotation>
                        <xs:documentation>Dieses Element übermittelt die Paketnummer der laufenden Aktenlieferung. Die Lieferung beginnt mit der Liefernummer 1.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
               </xs:sequence>
            </xs:extension>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
</xs:schema>
